#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER:$USER" /var/www/
# redirection
redirect="\\\trewrite ^/redirect_me https://www.github.com/Alausa2001 permanent;"
sed -e "51i ${redirect}" -i /etc/nginx/sites-available/default
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
# error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error.html
sudo sed -e "55i \\\terror_page 404 /error.html;" -i /etc/nginx/sites-available/default;
sudo sed -e "56i \\\tlocation = /error.html {\n\t\troot /var/www/html;" -i /etc/nginx/sites-available/default;
sudo sed -e "58i \\\t\tinternal;\n\t}" -i /etc/nginx/sites-available/default;
sudo service nginx restart
sudo service nginx start
