#!/usr/bin/env bash
# configures a server to listen to port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep nginx | head -1)"
