#!/usr/bin/env bash
# FizzBuzz Challenge
i=1
while [ $i -le 100 ];
do
	if (( i % 3 == 0 & i % 5 == 0 ))
	then
		echo "FizzBuzz"
		(( i++ ))
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
		(( i++ ))
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
		(( i++ ))
	else
		echo $i
		(( i++ ))
	fi
done
