#!/usr/bin/env bash
# This script is displaying "Best School" if the count reaches 4 it "bad luck is printed
# at 8 "good luck is printed
i=1
while [ $i -le 10 ];
do
	if [ $i = 4 ]
	then
		echo "bad luck"
		((i++))
	elif [ $i = 8 ]
	then
		echo "good luck"
		((i++))
	else
		echo "Best School"
		((i++))
	fi
done
