#!/usr/bin/env bash
# This script is displays 1 - 20 and count 4 "bad luck from china is echoed"
# at 9 "bad luck from japan is displayed"
# at 17 "bad luck from italy is diplayed"
i=1
while [ $i -le 20 ];
do
	echo $i
	case  $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
