#!/usr/bin/env bash
# run the webserver(nginx) with a user without sudo permissions

sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf*
sudo -u nginx service nginx start
