#!/usr/bin/env bash
# run the webserver(nginx) with a user without sudo permissions

sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf*
pkill apache2
sudo -u nginx service nginx start
